### ISSUE TITLE
How to patch darkice 1.2 to 1.3

### ISSUE THREAD

**Issue by prok0403** [rafael2k/darkice#116]
Hi,

Not really an issue, but I am not very experienced in how to patch a current darkice installation (version 1.2) on Ubuntu to darkice 1.3.
Maybe someone is willing to help me with this?
Many thanks in advance! 

KR
Kees

**Comment by DanielEckl** [comment]
I'd rather not "patch" the package that ships with Ubuntu (no matter what "patching" means for you in this context).

If you have the knowledge to compile things yourself, then I would suggest to build darkice from tarball and copy the resulting binary to your users ~/bin directory. I'm doing that since a long time now and found that most convenient.

If you don't have the knowledge to compile yourself, I'd rather recommend to upgrade to Ubuntu 16.10 in 2 weeks that ships darkice 1.3.

Building your own darkice 1.3 package for Ubuntu 16.04 is possible, of course, but this exceeds the task to build your own darkice as I suggested above, as it needs not only compile knowhow, but also packaging knowhow. Explaining this here would be beyond the scope of this issue tracker.

**Comment by prok0403** [comment]
-

**Comment by prok0403** [comment]
-
